sudo: required
services:
  - docker
before_install:
  - docker build -t harsh244/docker-react -f Dockerfile.dev .

script:
  - docker run harsh244/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-661056593567"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS
  secret_access_key:
    secret: $AWS_SECRET
